version: '3'
services:
  etl:
    image: fiveappetl
    tty: true
    volumes:
      - ./datalake/:/var/tmp/
      - ./etl/:/mnt/etl/
  # database:
  #   image: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: test
  #   volumes:
  #     - ./mysqldata/:/var/lib/mysql